# Generated by Django 2.2.7 on 2019-11-29 22:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='searched_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=[], size=None),
            preserve_default=False,
        ),
    ]
