# Generated by Django 2.2.8 on 2019-12-21 18:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191221_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='searched_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=15, null=True), size=None),
        ),
    ]
