# Generated by Django 2.2.8 on 2019-12-21 18:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191221_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='searched_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=15, null=True), size=None),
        ),
    ]
