# Generated by Django 2.2.8 on 2019-12-21 18:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191221_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='searched_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None),
        ),
    ]
