# Generated by Django 2.2.8 on 2019-12-21 23:35

import accounts.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191221_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='searched_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=accounts.models.default_array, null=True, size=None),
        ),
    ]
